# Generated by Django 4.0.1 on 2024-07-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер телефона'),
        ),
    ]
